USE RITS;

CREATE TABLE IF NOT EXISTS CLIENTE (
	ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,
	ENDERECO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PEDIDO (
	ID INTEGER NOT NULL PRIMARY KEY,
	COD_CLI INTEGER NOT NULL,
	DATA_CRIACAO VARCHAR(10) NOT NULL,
	STATUS VARCHAR(15) NOT NULL,
	FOREIGN KEY (COD_CLI) REFERENCES CLIENTE(ID)	
);

CREATE TABLE IF NOT EXISTS PRODUTO (
	ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	PRECO DECIMAL(5,2) NOT NULL,
	COD_PED INTEGER,
	FOREIGN KEY (COD_PED) REFERENCES PEDIDO(ID)
		ON DELETE CASCADE	
);